---
# tasks file for docker swarm manage instance

- meta: flush_handlers

- name: run docker swarm manage image
  become: yes
  become_user: docker
  docker:
    image: swarm
    command: manage -H :4000 --replication --advertise {{ docker_manage_private_ip }}:4000 consul://{{ docker_consul_private_ip }}:8500
    ports: 4000:4000
    expose: 4000
    detach: true
    state: started
  tags:
    - worker

- name: create directory for docker swarm log
  become: yes
  file:
    path: /var/log/docker
    state: directory
  tags:
    - worker

- name: install crontab to create docker swarm log
  become: yes
  cron:
    name: "Write docker swarm log"
    minute: "*/5"
    job: "{ echo '-----------'; { echo 'Date: '; date; } | tr '\\n' ' '; echo ' '; docker -H :4000 info; } >> /var/log/docker/docker_swarm.log 2>&1"
    state: present
  tags:
    - worker

- name: install logrotate for docker swarm log
  become: yes
  copy:
    src: docker_swarm
    dest: /etc/logrotate.d/docker_swarm
  tags:
    - worker
