# Runs parallel to delft3d simulation. Processes the delft3d netcdf ouput to new netcdf's and images.

FROM ubuntu
RUN apt-get update
RUN apt-get install python -y
RUN apt-get install python-dev -y
RUN apt-get install python-pip -y
RUN apt-get install libhdf5-serial-dev -y
RUN apt-get install wget -y
RUN wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.1.3.tar.gz
RUN tar -xvf netcdf-4.1.3.tar.gz
RUN cd netcdf-4.1.3 && ./configure && make && make install
RUN pip install numpy --upgrade
RUN pip install netcdf4
RUN apt-get install python-matplotlib -y
RUN mkdir /data
ADD dummy_plot_netcdf.py /data/dummy_plot_netcdf.py
WORKDIR /data
CMD python dummy_plot_netcdf.py

# docker run -v { workingdir }:/data/input:ro -v { workingdir }/processing:/data/output -t dummy_processing
